name: "sphinx"
on: [pull_request]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        sudo apt install pandoc
        python -m pip install --upgrade pip
        pip install -U sphinx
    - name: Build sphinx documentation
      run: |
        make html
